version: '3.8'

services:
  app:
    build:
        dockerfile: Dockerfile
    depends_on:
      - postgres-ismyburguer
      - mongodb-ismyburguer
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-ismyburguer:5432/ismyburguer
      - SPRING_DATASOURCE_USERNAME=ismyburguer
      - SPRING_DATASOURCE_PASSWORD=ismyburguer
      - SPRING_MONGO_DATASOURCE_URL=mongodb://ismyburguer:ismyburguer@mongodb-ismyburguer:27017/ismyburguer?authSource=admin
      - SPRING_MONGO_PASSWORD=ismyburguer
      - SPRING_MONGO_USERNAME=ismyburguer
    ports:
      - '8088:8080'
    networks:
      - ismyburguer-backend
  mongodb-ismyburguer:
    image: 'mongo:latest'
    container_name: mongodb-ismyburguer
    volumes:
      - mongodb-ismyburguer:/data/db
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=ismyburguer
      - MONGO_INITDB_ROOT_USERNAME=ismyburguer
    restart: on-failure
    ports:
      - '27017:27017'
    networks:
      - ismyburguer-backend
  postgres-ismyburguer:
    image: 'postgres:latest'
    restart: unless-stopped
    container_name: postgres-ismyburguer
    ports:
      - '5432:5432'
    volumes:
      - postgres-ismyburguer:/var/lib/postgresql/data
      - ./script-inicial.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=ismyburguer
      - POSTGRES_PASSWORD=ismyburguer
    networks:
      - ismyburguer-backend
networks:
  ismyburguer-backend:
    external: false
    driver: bridge
volumes:
  mongodb-ismyburguer:
  postgres-ismyburguer:
