include:
  - 'compose-base.yaml'

services:
  app:
    build:
        dockerfile: Dockerfile
    links:
      - postgres-ismyburguer
      - mongodb-ismyburguer
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-ismyburguer:5432/ismyburguer
      - SPRING_DATASOURCE_USERNAME=ismyburguer
      - SPRING_DATASOURCE_PASSWORD=ismyburguer
      - SPRING_MONGO_DATASOURCE_URL=mongodb://ismyburguer:ismyburguer@mongodb-ismyburguer:27017/ismyburguer?authSource=admin
      - SPRING_MONGO_PASSWORD=ismyburguer
      - SPRING_MONGO_USERNAME=ismyburguer
    ports:
      - '127.0.0.1:8080:8080'
    networks:
      - ismyburguer-backend