services:
  mongodb-ismyburguer:
    image: 'mongo:latest'
    container_name: mongodb-ismyburguer
    volumes:
      - mongodb-ismyburguer:/data/db
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_PASSWORD}
    restart: unless-stopped
    ports:
      - '127.0.0.1:27088:27017'
    networks:
      - ismyburguer-backend
  postgres-ismyburguer:
    image: 'postgres:latest'
    container_name: postgres-ismyburguer
    restart: unless-stopped
    ports:
      - '127.0.0.1:5433:5432'
    volumes:
      - postgres-ismyburguer:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - ismyburguer-backend
networks:
  ismyburguer-backend:
    external: false
    driver: bridge
volumes:
  mongodb-ismyburguer:
  postgres-ismyburguer: