logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR

spring:
  docker:
    compose:
      enabled: true
      file: compose.yaml
      ports:
        - '5005:5005'
        - '8088:8080'
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        default_schema: public
        default_catalog: public
  data:
    # MONGODB properties
    mongodb:
      user: ${SPRING_MONGO_USERNAME}
      password: ${SPRING_MONGO_PASSWORD}
      uri: ${SPRING_MONGO_DATASOURCE_URL}