logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR

server:
  port: 8088

management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: '*'

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: false
    enable: false
  show-actuator: true

spring:
  liquibase:
    enabled: false
  # Quartz
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: true
  # Docker
  thread-executor: standard
  docker:
    compose:
      enabled: true
      file: compose.yaml
      ports:
        - '5005:5005'
        - '8088:8080'
      volumes:
        - postgres-ismyburguer:/var/lib/postgresql/data
        - mongodb-ismyburguer:/data/db
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        default_schema: public
        default_catalog: public
  data:
    # MONGODB properties
    mongodb:
      user: ${SPRING_MONGO_USERNAME}
      password: ${SPRING_MONGO_PASSWORD}
      uri: ${SPRING_MONGO_DATASOURCE_URL}