apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: mongodb-ismyburguer
  name: mongodb-ismyburguer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
