apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongodb-ismyburguer
  name: mongodb-ismyburguer
spec:
  type: ClusterIP
  selector:
    name: mongodb-ismyburguer
  ports:
    - port: 27018
      targetPort: 27017
