apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: postgres-ismyburguer
  name: postgres-ismyburguer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
