apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres-ismyburguer
  name: postgres-ismyburguer
spec:
  type: NodePort
  selector:
    name: postgres-ismyburguer
  ports:
    - port: 5433
      targetPort: 5432
      nodePort: 31432
